#!/bin/bash

export PS1='PairUp!™ \w\$ '

alias links=elinks

export VISUAL=vim
export EDITOR=$VISUAL
set -o vi

export GIT_AUTHOR_EMAIL=ingy@ingy.net
export GIT_AUTHOR_NAME="Ingy döt Net"
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
export GIT_COMMITTER_AUTHOR=$GIT_AUTHOR_AUTHOR
