#!/bin/bash

for n in ~/.sh/*; do
    source $n || echo "Trouble sourcing: $n"
done
source ~/.,

export PS1='PairUp!™ \w\$ '
sourceif ~/.bashrc../git-prompt

alias links=elinks

export VISUAL=vim
export EDITOR=$VISUAL
set -o vi

export GIT_AUTHOR_EMAIL=ingy@ingy.net
export GIT_AUTHOR_NAME="Ingy döt Net"
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
export GIT_COMMITTER_AUTHOR=$GIT_AUTHOR_AUTHOR
